export const types = Object.freeze({
    START_FETCHING:     'START_FETCHING',
    STOP_FETCHING:      'STOP_FETCHING',
    FILL_NOTIFICATION:  'FILL_NOTIFICATION',
    CLEAR_NOTIFICATION: 'CLEAR_NOTIFICATION',
});
